- virtinst/osdict.py
Arguments to logging needs to be individual args, otherwise it
fails with "not enough arguments for format string"                             
Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>
> virt-install: Fix guest-os deprecation msg

- man/virt-install.pod
The example commentary says Fedora 20, so make the command line match that.
> virt-install.pod: make example command match commentary

- virtinst/domcapabilities.py
With libvirt-python >= 4.4.0 and libvirt < 4.4.0 we would receive
libvirt.libvirtError exception because the python binding knows about
the function but it's not supported by libvirt.  However, in case that
the python binding is older then 4.4.0 it will raise AttributeError
because the function is not implemented in python binding as well.
Signed-off-by: Pavel Hrdina <phrdina@redhat.com>
Fixes #57
> virtinst: fix detection if baselineHypervisorCPU API is available

- man/virt-install.pod
The flag for hiding the KVM hypervisor signature has too many "=" signs.
> Fix typo in virt-install man page

- po/pt_BR.po
This fixes a small mistake in the pt_BR translation. Currently it is translating "key" with the same word used for cryptographic keys instead of the word for keyboard keys.
Enviar Chave -> Enviar Tecla
> Fix Send Key translation in pt_BR

- CONTRIBUTING.md
"python -m pytest --uitest" does not work as expected.
> CONTRIBUTING: Fix uitests test name

- virtinst/capabilities.py
Hello
Just noticed that when creating new aarch64 machine, "virt-5.0" entry appeared twice.
This PR tries to fix this problem by avoiding the same alias name.
before patch:
after patch:
> Fix duplicate machine type entry in aarch64 when creating new VM

- virtManager/addhardware.py
Both are needed to install Windows 10 Arm64 from ISO.
Just FYI, if you want to test this: libvirt currently doesn't create correct USB cdrom devices, which breaks the installer. More info is available in the pending merge request for it: https://gitlab.com/libvirt/libvirt/-/merge_requests/19
> Add USB cdrom and ramfb video

- virtinst/install/installertreemedia.py
When starting many virt-install processes in parallel, some often crash
with
ERROR    [Errno 17] File exists: '/home/kstest/.cache/virt-manager/boot'
Fix that by ignoring existing directories instead of explicitly testing
for existence.
The `exist_ok` parameter exists since Python 3.2, and the minimum
supported version is 3.4 now.
> virtinst: Fix TOCTOU race in user scratch dir creation

- virt-manager.spec
It looks like there is no %{python3} macro in CentOS 8.
Using %{__python3} should be always safe.
Signed-off-by: Igor Ryzhov <iryzhov@nfware.com>
> spec: fix python macro

- tests/__init__.py
Various checks in the test suite try to match for error/status messages, so using a localized libvirt (or even using translations of an installed version of virt-manager in the system) makes those check fail. Hence, force (using `$LANG`, and unsetting `$LANGUAGE`) an English UTF-8 locale.
Thanks Cole Robinson for spotting the right place where to inject the locale settings.
Fixes: #199
Signed-off-by: Pino Toscano <ptoscano@redhat.com>
> tests: force an English UTF-8 locale

- tests/data/cli/compare/virt-install-singleton-config-2.xml
- tests/test_cli.py
- virtinst/cli.py
- virtinst/domain/cputune.py
This adds the following suboptions to configure the
\<domain\>\<cputune\>\<iothreadpin\> list:
* iothreadpin[0-9]*.iothread
* iothreadpin[0-9]*.cpuset
\<iothreadpin\> only has two suboptions, but due to its `[0-9]*` nature, I don't think it can be simplified from an XMLChildProperty to an XMLProperty. Feel free to correct me on this if I misunderstood how that mechanism works.
> cli: --cputune: add iothreadpin[0-9]* config

- tests/data/cli/compare/virt-install-singleton-config-2.xml
- tests/test_cli.py
- virtinst/cli.py
- virtinst/domain/os.py
libvirt 7.2.0 introduced support for a list of firmware features
that should or should not be present. Libvirt takes these into
account when auto-selecting a firmware. Currently supported
features are `enrolled-keys` and `secure-boot`.
This also bumps the minimum version for the `singleton-config-2`
test to 7.2.0.
---
Keeping from creating way to many XMLChildProperty with this one caused me some headache until I notice how `<cpu><numa><cell>` is handled using `relative_xpath=""`. Much neater like this!
> cli: --boot: add support of firmware features

- virtinst/install/urlfetcher.py
Fixes: #291
The `text=` keyword was added in Python 3.7 "as a more readable
alias for `universal_newlines=`". This commit switches to the
old form of the name, for backwards compatibility with Python 3.6,
the default Python3 version on Ubuntu 18.04 and RHEL 8.
When support for Python 3.6 is no longer needed, this change can
be reverted.
> urlfetcher: Make `check_output` call compatible with Python 3.6

- tests/data/cli/compare/virt-install-singleton-config-2.xml
- tests/test_cli.py
- virtinst/cli.py
- virtinst/domain/cputune.py
This should add all missing options to --cputune as of 7.6.0 and bring the ordering in the XML in line with libvirt's own output.
> cli: --cputune: implement missing options

- tests/data/cli/compare/virt-install-many-devices.xml
- tests/data/cli/compare/virt-xml-add-host-device.xml
- tests/data/testdriver/testsuite.xml
- tests/test_cli.py
Libvirt > 7.6.0 introduced uniqueness checks for host devices in
```
commit 9c3b6b7a82373b680a0e4ba4f1baebcb430d45b2
Author: Shalini Chellathurai Saroja <shalini@linux.ibm.com>
Date:   Fri Jun 18 12:46:12 2021 +0200
conf: verify for duplicate hostdevs
It is possible to define/edit(in shut off state) a domain XML with
same hostdev device repeated more than once, as shown below. This
behavior is not expected. So, this patch fixes it.
```
The test suite was mistakenly relying on being able to add the same device twice, but is trivially fixed to use unique devices
> Fix problems with test suite in new libvirt

- virtinst/install/installerinject.py
Commit c6b5f22fa61d started passing the --owner argument to cpio when injecting files into the initrd to comply with the more strict requirements introduced by systemd starting with Fedora 30.
However, cpio only started accepting the +uid:+gid syntax in version 2.12, which means that the fix actually broke the
initrd inject functionality completely in RHEL 7 and other distros that don't include a recent enough cpio.
Use the user:group syntax instead, which is understood by all versions of cpio, including non-GNU ones.
> installerinject: Use root:root instead of +0:+0 as owner

- virtinst/osdict.py
Each OS may specify which kernel argument is needed to specify the
installation source; use it as primary source, falling back to the
current logic. This should help supporting new OSes OOTB.
Signed-off-by: Pino Toscano <ptoscano@redhat.com>
> osinfo: use the OS kernel-url-argument if available

- virtinst/install/installerinject.py
Any of the commands involved in injecting files into an initrd could fail, and if that happens we should interrupt the installation instead of proceeding as if nothing had happened.
> installerinject: Add error detection for initrd injection

- tests/test_cli.py
- virtinst/domain/launch_security.py
The code was only checking the manual approach to enabling UEFI, not the
modern automatic approach.
Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>
> virtinst: fix check for UEFI in SEV setup

- virtinst/osdict.py
Accidentally changed in
commit 302ef1f09669516677d83979536617f1705e1c75
Author: Daniel P. Berrangé <berrange@redhat.com>
Date:   Fri Nov 26 18:51:49 2021 +0000
virtinst/osdict: add a property for the OsinfoDb object
Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>
> virtinst: fix return type in guess_os_by_iso

- data/virt-manager.desktop.in
Adding this keyword will help finding the virtual machine manager application from start menu.
> Add "vmm" shortcut keyword

- setup.py
Quoting https://github.com/pypa/setuptools/issues/3227
"Setuptools >= 61, intentionally changes the way packages are built in the
sensec that it will try to find files and fail if something is weird.
Empty packages (like this one), are asked to explicitly add packages=[]
to their configuration.
This intentional change in behaviour is described in
https://setuptools.pypa.io/en/latest/history.html#v61-0-0."
Bug: https://bugs.gentoo.org/836645
Signed-off-by: Peter Alfredsen <crabbedhaloablution@icloud.com>
> setup: add bits for setuptools-61

- setup.py
+ ./setup.py configure --default-hvs qemu,xen,lxc
error: Multiple top-level packages discovered in a flat-layout: ['po', 'ui', 'man', 'data', 'virtinst', 'virtManager'].
To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.
If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:
1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names
To find more information, look for "package discovery" on setuptools docs.
Downstream bug report: https://bugzilla.redhat.com/2113754
> Fix build with setuptools 61+

- virtinst/install/installerinject.py
Building virt-manager on macOS with tests enabled fails with the following error:
```
testCLI0051virt_install_initrd_inject: cpio: root:root: invalid group
```
Setting the owner to 0:0 fixes the issue.
> tests: cpio: set owner to 0:0

- tests/test_capabilities.py
- virtinst/domcapabilities.py
- virtinst/guest.py
v1 -> v2: Follow the original behavior in case of talking to older libvirt.
Libvirt domcaps can advertise the redirect devices and spicevmc channel devices since v8.9.0.
Virt-install adds usb redirdevs and spicevmc channels by default on x86.
This patchset adds checks to avoid using redirect devices/spicevmc channel devices when not supported by the target qemu.
> Check availability of usb redirdevs and spicevmc channels in domcaps

- tests/data/cli/compare/virt-clone-serial.xml
- tests/data/cli/virtclone/clone-serial.xml
- tests/test_cli.py
- virtinst/cloner.py
Before this, on clone the serial file would remain the same for the cloned
domain. This doesn't make much sense as the output would be an intermix of two
unrelated output sequences.
Here we apply the same filename changing algorithm, as with disk files.
> cloner: clone serial files 

- man/virt-install.rst
It is common on x86 and other architectures to install a guest from network by using "--boot hd,network" with virt-install - as long as the hard disk is not bootable yet, the installation will be started via network, and once it finished, the guest can boot from hd during the next reboot.
However, this does not work on s390x since this architecture only supports one single boot device to be passed to the guest. Thus add a note to the documentation to avoid that people are running again into this common pitfall.
Buglink: https://bugzilla.redhat.com/show_bug.cgi?id=2032472
> man/virt-install: Add a note about different behavior of --boot on s390x

- virtManager/hoststorage.py
- virtManager/lib/inspection.py
- virtManager/object/domain.py
- virtinst/guest.py
Commit f107e3998908 ("Switch to more traditional logging structure", 2019-06-17) replaced "logging.exception" with "log.exception", effectively shifting the argument lists 4 characters to the left. The second and further lines of multiline invocations were not accordingly unindented, however, which ended up setting a suboptimal precedent as well. Unindent those lines now.
Reported-by: Cole Robinson <crobinso@redhat.com>
> fix indentation of multiline log.exception() invocations

- virtinst/storage.py
When cloning using libvirt APIs the function virStorageVolCreateXMLFrom is used.  However name and permissions are taken from the new XML [1]. By copying the permissions (only the mode is used) we can avoid some unexpected issues.
[1] https://libvirt.org/html/libvirt-libvirt-storage.html#virStorageVolCreateXMLFrom
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2115153
> virt-clone: Copy disk permissions as well

- tests/data/cli/compare/virt-install-many-devices.xml
- virtinst/devices/filesystem.py
When specifying the socket.source option for filesystem devices, like
this:
--filesystem type=mount,driver.type=virtiofs,source.socket=/xyz.sock,target.dir=tag1
virt-install is writing the xml as:
<filesystem type="mount">
<source>
<socket>/xyz.sock</socket>
</source>
<target dir="tag1"/>
<driver type="virtiofs"/>
</filesystem>
This produces an error such as:
ERROR missing source information for device mount_tag1
But the socket should be an attribute of source rather than a child
element. After this patch, the same command results in the following XML
and no error is produced:
<filesystem type="mount">
<source socket="/xyz.sock"/>
<target dir="tag1"/>
<driver type="virtiofs"/>
</filesystem>
Resolves: RHEL-1126
Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>
> Fix filesystem socket.source

- ui/details.ui
Under OS information the Applications list was too narrow to read, so I have enabled expanding horizontally.
Before:
After:
> Fixed issue where applications list was too narrow to read in OS info

- virtManager/config.py
- virtManager/details/console.py
- virtManager/details/sshtunnels.py
- virtManager/details/viewers.py
- virtManager/object/domain.py
Currently, when there are multiple graphics devices, the first graphics
device is always selected as the graphical console. For the following
configuration:
<graphics type="egl-headless">
<gl rendernode="/dev/dri/renderD128"/>
</graphics>
<graphics type="spice" autoport="yes">
<listen type="address"/>
<image compression="off"/>
<gl enable="no"/>
</graphics>
virt-manager will report an error:
Cannot display graphical console type 'egl-headless'
The patch will iterate through all graphics devices to try to select the
first embeddable graphics device as graphical console.
>  console: Select the first embeddable graphics device as graphical console

- virtManager/details/serialcon.py
Replace Gtk.Box.add() with Gtk.Box.pack_start() to place the VTE terminal widget. This enables horizontal expansion/filling the terminal widget when resizing the serial console window.
To test: enlarge the window beyond 80 columns and run the `resize` command. Run `stty -a` to verify the new dimensions.
> Allow serial console resize to beyond 80 columns.

- setup.py
Newer versions of `setuptools` (62.4.0+) provide a `setuptools.command.build` module to replace `distutils.command.build`; hence, try to use it when available, falling back to `distutils` otherwise as already done.
Include the switch to `setup()` to ease the migration.
> build: switch fully to setuptools when possible

- virtManager/error.py
- virtManager/vmwindow.py
Use [GtkFileChooserNative](https://docs.gtk.org/gtk3/class.FileChooserNative.html) instead of [GtkFileChooserDialog](https://docs.gtk.org/gtk3/class.FileChooserDialog.html) to integrate better with the platform (e.g. use the portal implementation when run with GTK_USE_PORTAL=1, resulting in the KDE Frameworks implementation being used when
xdg-desktop-portal-kde is in use). Quoting from the [GtkFileChooserDialog doc](https://docs.gtk.org/gtk3/class.FileChooserDialog.html):
> If you want to integrate well with the platform you should use the
> GtkFileChooserNative API, which will use a platform-specific dialog if
> available and fall back to GtkFileChooserDialog otherwise.
Also replace the use of [GTK_STOCK_CANCEL](https://docs.gtk.org/gtk3/const.STOCK_CANCEL.html) and …
> Use GtkFileChooserNative

- .github/workflows/test-against-libvirt-git.yml
Periodic job to run the test suite against libvirt.git
This is currently failing, so I'll disable it when it hits git master. I have patches for libvirt.git but they haven't hit the mailing list yet.
@pinotree @phrdina thoughts?
> ci: Add test-against-libvirt-git.yml

- tests/data/capabilities/qemu-riscv64-domcaps.xml
- tests/data/capabilities/qemu-riscv64.xml
- tests/data/cli/compare/virt-install-aarch64-cloud-init.xml
- tests/data/cli/compare/virt-install-riscv64-cdrom.xml
- tests/data/cli/compare/virt-install-riscv64-cloud-init.xml
- tests/data/cli/compare/virt-install-riscv64-graphics.xml
- tests/data/cli/compare/virt-install-riscv64-headless.xml
- tests/data/cli/compare/virt-install-riscv64-kernel-boot.xml
- tests/data/cli/compare/virt-install-riscv64-unattended.xml
- tests/test_cli.py
- virtinst/guest.py
- virtinst/install/installer.py
Make most things work out of the box when importing existing and upcoming disk images. As a side-effect, make importing aarch64 cloud images smoother too.
> Improve riscv64 support

- virt-manager.spec
- virtManager/xmleditor.py
The only thing that GtkSourceView gives us is syntax highlighting and
auto-indent. When this library is not available, we can still offer xml
editing with a plain textview with very little lost functionality.
Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>
> xmleditor: make gtksourceview optional

- tests/data/cli/compare/virt-install-many-devices.xml
- tests/data/cli/compare/virt-install-mdev-devices.xml
- tests/test_cli.py
- tests/test_nodedev.py
The test driver was broken for some time and our mdev tests were failing on most libvirt versions. Recently this was fixed in libvirt 10.4.0 so skip these tests unless we have new enough libvirt.
This requires extracting some mdev devices from many-devices test case.
> tests: skip mdev tests for libvirt older than 10.4.0

- man/virt-install.rst
- virtinst/cli.py
While the shorthand saves a tiny bit of typing, it is confusing to people coming from QEMU, where `-cpu host` is the equivalent of our `--cpu host-passthrough`. It's better to stick with the unambiguous names used by libvirt.
Besides, the GUI already uses "host-model" throughout, so advocating its use in the CLI too increases the internal consistency.
https://issues.redhat.com/browse/RHEL-40003
> cli: Deprecate -cpu host

- tests/data/cli/compare/virt-install-aarch64-cdrom.xml
- tests/data/cli/compare/virt-install-aarch64-cloud-init.xml
- tests/data/cli/compare/virt-install-aarch64-firmware-no-override.xml
- tests/data/cli/compare/virt-install-aarch64-kvm-gic.xml
- tests/data/cli/compare/virt-install-aarch64-machdefault.xml
- tests/data/cli/compare/virt-install-aarch64-machvirt.xml
- tests/data/cli/compare/virt-install-arm-defaultmach-f20.xml
- tests/data/cli/compare/virt-install-arm-kvm-import.xml
- tests/data/cli/compare/virt-install-riscv64-cdrom.xml
- tests/data/cli/compare/virt-install-riscv64-cloud-init.xml
- tests/data/cli/compare/virt-install-riscv64-kernel-boot.xml
- tests/data/cli/compare/virt-install-riscv64-unattended.xml
- tests/data/cli/compare/virt-install-s390x-default.xml
- tests/test_cli.py
- virtinst/guest.py
This adds test case for s390x where we do not set graphics by default to have full test code coverage.
> Add default graphics for aarch64 and riscv with virt machine

- tests/test_disk.py
- virtManager/hoststorage.py
- virtinst/devices/disk.py
In current virt-manager, the storage browser could be extremely slow (or even unusable), when the first pool shown has many files:
https://github.com/virt-manager/virt-manager/assets/2109893/92fa74cd-3934-47be-a58e-271b2566e1c7
After debugging it shows that following code in virtinst/devices/disk.py, `DeviceDisk.path_in_use_by`:
```python
volmap = dict((vol.backing_store, vol)
for vol in conn.fetch_all_vols() if vol.backing_store)
```
takes 0.03s on my laptop every time, and as `vmmHostStorage._populate_vols()` calls `DeviceDisk.path_in_use_by` for every vol, when there are thousands of volumes in a pool (which is usually the case when pool is a local directory), it could take at least half a minute for one call to `_populate_vols()`.
This pull request attempts to fix this by adding a new …
> Improve storage browser performance

- tests/data/cli/compare/virt-install-location-iso-and-cloud-init.xml
- tests/test_cli.py
- virtinst/install/installer.py
So far, --cloud-init is ignored when --location is specified.
Resolves: virt-manager#469
Thanks to @larsch for the initial fix PR #472
This new version of the fix adds a new test case as suggested by @crobinso.
In addition, I've been using this feature repeatedly for the past few hours with no issue with my limited use case: running Ubuntu Server 22.04 autoinstall by passing both cloud-init user-data and the "autoinstall" kernel command line argument.
> virtinstall: Fix --location and --cloud-init conflict

- tests/data/cli/compare/virt-install-many-devices.xml
- tests/test_cli.py
- virtinst/cli.py
- virtinst/devices/interface.py
Add new `--network backend.type` attribute, libvirt currently supports only `passt`. If not network type is specified virt-install will pick `user` type as it is required for `passt` backend.
This also introduces support to specify portForward and specifying port range as well.
For more details see [1].
[1] <https://libvirt.org/formatdomain.html#userspace-slirp-or-passt-connection>
Fixes: https://github.com/virt-manager/virt-manager/issues/488
> virt-install: implement passt backend for user network interface

- man/virt-xml.rst
- tests/data/cli/compare/virt-xml-change-graphics-and-video.xml
- tests/data/cli/compare/virt-xml-change-spice-to-vnc.xml
- tests/data/cli/compare/virt-xml-edit-graphics-spice-gl.xml
- tests/data/cli/compare/virt-xml-multiple-edit.xml
- tests/data/cli/compare/virt-xml-remove-spice-graphics.xml
- tests/data/testdriver/testsuite.xml
- tests/test_cli.py
- virtManager/object/domain.py
- virtinst/cli.py
- virtinst/devices/device.py
- virtinst/devices/graphics.py
- virtinst/devices/video.py
- virtinst/guest.py
- virtinst/virtxml.py
When switching between Spice and VNC graphics it is usually not enough to just change the graphics type. For example spice uses additional devices to offer full functionality and they are added by virt-install/virt-manager whenever spice graphics is used.
With these changes using:
`virt-xml {VM} --edit --graphics vnc`
will remove all Spice only related devices as well. Previously this invocation would fail as libvirt doesn't allow having other Spice devices without Spice graphics.
There might be use cases where video device needs to be changed together with graphics or in general any other devices changed together. To make that happen we now allow multiple edits at the same time. So for example:
`virt-xml {VM} --edit --graphics vnc --edit --video virtio`
will now work.
> virt-xml: make it easier to switch between Spice and VNC graphics

- tests/data/capabilities/kvm-x86_64-domcaps-latest.xml
- tests/data/cli/compare/virt-install-hyperv_disable_vpindex.xml
- tests/data/cli/compare/virt-install-hyperv_no_domcaps.xml
- tests/data/cli/compare/virt-install-kvm-win10.xml
- tests/data/cli/compare/virt-install-kvm-win2k3-cdrom.xml
- tests/data/cli/compare/virt-install-many-devices.xml
- tests/data/cli/compare/virt-install-os-detect-fail-fallback.xml
- tests/data/cli/compare/virt-install-osinfo-win7-unattended.xml
- tests/data/cli/compare/virt-install-unattended-remote-cdrom.xml
- tests/data/cli/compare/virt-install-w2k3-cdrom.xml
- tests/data/cli/compare/virt-install-win11.xml
- tests/data/cli/compare/virt-install-win7-uefi.xml
- tests/test_cli.py
- virtinst/capabilities.py
- virtinst/cli.py
- virtinst/domain/clock.py
- virtinst/domain/features.py
- virtinst/domcapabilities.py
- virtinst/support.py
This patch series doesn't add support for `vendor_id` feature for now, that will be done in future.
We will not enable `reset` as it is not exported by modern Hyper-V versions and `reenlightenment` is mostly useful when migrating VMs with Hyper-V running inside and requires some other bits to make it work correctly.
Fixes #154
> Add support for missing Hyper-V features and enable most of them by default

- virtManager/details/sshtunnels.py
Fix console config validation for an edge case where both libvirt and Spice/VNC TCP connection are on localhost. Transport over TCP does not necessarily mean that libvirt connection is to a remote host.
Compare libvirt and graphics device addresses to localhost individually. Raise an error only when guest device is bound to localhost but libvirt connection is non-local (remote).
Validation that prevents fully local TCP seems to go back all the way to bc13c302de4 ("console: Warn if qemu+tcp URI and listen == 127.0.0.1").
> console: allow localhost connections over TCP

- tests/uitests/data/live/uitests-firmware-efi.xml
- virtManager/object/domain.py
- virtinst/support.py
If the VM has implicit TPM state, use the VIR_DOMAIN_UNDEFINE_KEEP_TPM flag to preserve that state when renaming the VM (if libvirt is new enough).
The state is stored based on VM UUID and nothing else, and the UUID is preserved during rename, so we don't need to do any of the same trickery that's required for nvram duplication.
> domain: Use KEEP_TPM flag for domain rename

- ui/snapshotsnew.ui
- virtManager/details/snapshots.py
Current code will take a screenshot when the 'New Snapshot' dialog is initially launched, and then use that cached content as the screenshot for the snapshot... which may be totally out of date by the time the user enters all the snapshot info.
Instead, drop the snapshot preview UI in the 'New Snapshot' wizard entirely, and use a screenshot that is fetched after the user actually clicks 'Finish'
> snapshots: Don't save outdated screenshot data

- tests/test_cli.py
- virtinst/cli.py
- virtinst/virtinstall.py
- virtinst/virtxml.py
This series cleans up a bunch of miscellaneous things with virt-xml option processing.
The main bit it adds a `Action` class, which contains all the data to describe a single XML operation like `--edit 1 --disk path=/foo` or `--add-device --network default`, etc. This does not add any new functionality, but it cleans up a lot of mess that would prevent adding proper multi action support in the future.
Commits that follow on from that are small bugfixes and code improvements in the same area.
> virt-xml: cleanup action handling in preparation for multi --edit support

- man/virt-xml.rst
- tests/data/cli/compare/virt-xml-convert-to-q35-numports.xml
- tests/data/cli/compare/virt-xml-convert-to-q35.xml
- tests/data/cli/virtxml/convert-to-q35-win10-in.xml
- tests/data/xmlparse/convert-to-q35-f39-in.xml
- tests/data/xmlparse/convert-to-q35-f39-out.xml
- tests/data/xmlparse/convert-to-q35-win10-in.xml
- tests/data/xmlparse/convert-to-q35-win10-out.xml
- tests/test_cli.py
- tests/test_xmlparse.py
- virtinst/cli.py
- virtinst/guest.py
- virtinst/virtxml.py
This PR is on top of https://github.com/virt-manager/virt-manager/pull/727 since they overlap
This adds `virt-xml --edit --convert-to-q35`. The XML bits we actually edit are layed out in https://github.com/virt-manager/virt-manager/issues/720 plus converting ich6 -> ich9 sound, and clearing disk `<address>` blocks.
In my limited testing, VMs handle this mostly OK:
* Fedora 39 reboots fine and everything works. Even manually converting virtio storage to `sata` config and Fedora doesn't mind.
* Win10 will fail to boot. After a couple reboots it drops you to the repair menu. If you boot once into safe mode, it seems to figure everything out, and subsequent reboots boot fine.
* Win11 rejects machine=pc in the first place, so we shouldn't need to worry about that.
> virt-xml: add `--edit --convert-to-q35`

- man/virt-xml.rst
- tests/data/cli/compare/virt-xml-convert-to-vnc-vdagent.xml
- tests/data/cli/compare/virt-xml-convert-to-vnc.xml
- tests/data/xmlparse/convert-to-vnc-empty-in.xml
- tests/data/xmlparse/convert-to-vnc-empty-out.xml
- tests/data/xmlparse/convert-to-vnc-has-vnc-in.xml
- tests/data/xmlparse/convert-to-vnc-has-vnc-out.xml
- tests/data/xmlparse/convert-to-vnc-spice-devices-in.xml
- tests/data/xmlparse/convert-to-vnc-spice-devices-out.xml
- tests/data/xmlparse/convert-to-vnc-spice-manyopts-in.xml
- tests/data/xmlparse/convert-to-vnc-spice-manyopts-out.xml
- tests/test_cli.py
- tests/test_xmlparse.py
- virtinst/cli.py
- virtinst/devices/video.py
- virtinst/guest.py
- virtinst/virtxml.py
This series adds a `virt-xml --convert-to-vnc` option, for handling everything I can think of to try and convert an existing VM to use VNC.
The primary usecase is spice->VNC, with particular emphasis on the case where spice is no longer available for the distro, like certain RHEL versions. So we strip out all spice-dependent devices like `qxl`, `spicevmc` bits, etc. Cockpit is already opencoding a limited version of this, but they would prefer if virt-xml handles it. Their code is here: https://github.com/cockpit-project/cockpit-machines/blob/main/src/libvirt-xml-update.js#L309
This also establishes a new pattern with `--convert-to-X` style compound operations for virt-xml, which we can follow for future `--convert-to-q35` for example. We could add suboptions if users need to opt out of …
> virt-xml: add `--convert-to-vnc`

- virtManager/systray.py
Latest upstream release was back in 2012 and the new libayatana-appindicator project is present in all distribution supported by libvirt.
> virtManager: drop libappindicator usage

- tests/test_cli.py
- virtinst/cli.py
- virtinst/virtinstall.py
Recently there was a case internally where someone was using `--osinfo detect=on,require=off`, media detection was failing, but the user didn't notice. In this case, virt-install will warn that `generic` OS is being used, so there was already a warning. But this changes things to make warnings more explicit that detection failed, and if that's unexpected to the user, they should file a bug.
This also changes `--osinfo detect=on` to imply `require=on` instead of `require=off`. That was a bug
> Tweak `--osinfo require=off` behavior to print more warnings

- man/virt-install.rst
- virtinst/domain/launch_security.py
Fix no longer valid URL fragments, wrap at 80th column, remove dots that follow only a few links.
> Update libvirt.org links

- data/org.virt-manager.virt-manager.gschema.xml
- tests/uitests/test_livetests.py
- tests/uitests/test_prefs.py
I think this is a better default than the current `Only when Fullscreen`, which is the same as `Never` for VM windowed mode.
I wrote my reasoning here:
https://github.com/virt-manager/virt-manager/issues/747
> switch console default to Scale Display->Always

- .packit.yaml
- drop all the architectures (and thus building only on x86_64): virt-manager has no architecture-specific installation bits, and thus it builds in the same way on every architecture; hence no need to explicitly test on various architectures
- test on all the supported Fedora versions (Rawhide included): this way it is possible to check that older versions are still supported, at least when building
> ci: tweak Packit configuration

- man/virt-manager.rst
- tests/uitests/lib/app.py
- tests/uitests/test_cli.py
- virtManager/virtmanager.py
This changes some of the bits I discussed in https://github.com/virt-manager/virt-manager/issues/731
* Add `SSH_ASKPASS_REQUIRE=force` by default
* Add a stub `--fork` option
* Add `VIRT_MANAGER_DEFAULT_FORK=yes|no` env variable to opt into specific forking behavior
* Document it all in the man page
* Switch the default from `--fork` to `--no-fork`
Everything before the default switch is a no brainer. Question is do we want to switch the fork default now, or hold off. 
I think the only people that may be unknowingly depending on fork behavior are users who 1) use ssh-askpass and 2) launch virt-manager from the terminal. That may in fact be zero users.
The argument against switching the default is 1) I might have missed a usecase and this will generate unexpected complaints, 2) the …
> virt-manager fork + ssh changes

- man/virt-install.rst
From manual
```
--tpm
Syntax: --tpm TYPE[,OPTIONS]
Configure a virtual TPM device. Examples:
--tpm /dev/tpm
Convenience option for passing through the hosts TPM.
--tpm emulator
Request an emulated TPM device.
--tpm default
Request virt-install to fill in a modern recommended default
Use --tpm=? to see a list of all available sub options.  Complete details at https://libvirt.org/formatdomain.html#elementsTpm
```
"none" is not listed as an option and running `virt-install  --tpm=? | grep -i  none` also returns nothing.
This adds a note that `none` can be used to disable TPM device
> virt-install: add a note that tpm can be effectively disabled by passing `none`

- tests/data/cli/compare/virt-install-memory-hotplug.xml
- virtinst/domain/cpu.py
Currently we will only apply the default `--cpu mode=host-passthrough` config when _no_ `--cpu` config is passed. But this means if a user configures ex. cpu `<topology>`, we don't set `host-passthrough` and they get the libvirt/qemu default baseline CPU.
Instead, only skip the default config if the user manually specified a `mode` or `model` value directly
https://issues.redhat.com/browse/RHEL-65371
> virt-install: use default `--cpu` mode more often

- man/virt-install.rst
- tests/data/cli/compare/virt-install-win11-no-uefi.xml
- tests/data/cli/compare/virt-xml-edit-boot-uefi-off.xml
- tests/data/testdriver/testdriver.xml
- tests/test_cli.py
- virtManager/object/domain.py
- virtinst/cli.py
- virtinst/guest.py
Add `--boot uefi=off` for opting out of uefi when virt-install would default to it, and for virt-xml to clear out all UEFI config for an existing VM
Resolves: https://github.com/virt-manager/virt-manager/issues/692
> Add `--boot uefi=off`

- man/virt-install.rst
- tests/data/cli/compare/virt-install-many-devices.xml
- tests/test_cli.py
- virtinst/cli.py
Roughly mirroring `podman run -p` syntax. Example:
--network backend.type=passt,portForward=123:456,portForward1=127.0.0.1:8080:80/udp
Resolves: https://github.com/virt-manager/virt-manager/issues/751
> cli: add `--network portForward=8080:80` convenience syntax

- man/virt-install.rst
- tests/data/cli/compare/virt-install-aarch64-machdefault.xml
- tests/data/cli/compare/virt-install-aarch64-machvirt.xml
- tests/data/cli/compare/virt-install-arm-defaultmach-f20.xml
- tests/data/cli/compare/virt-install-arm-virt-f20.xml
- tests/data/cli/compare/virt-install-linux2020.xml
- tests/data/cli/compare/virt-install-riscv64-cdrom.xml
- tests/data/cli/compare/virt-install-riscv64-cloud-init.xml
- tests/data/cli/compare/virt-install-riscv64-graphics.xml
- tests/data/cli/compare/virt-install-riscv64-headless.xml
- tests/data/cli/compare/virt-install-riscv64-kernel-boot.xml
- tests/data/cli/compare/virt-install-riscv64-unattended.xml
- tests/test_cli.py
- virtManager/details/details.py
- virtManager/preferences.py
- virtinst/domain/cpu.py
- virtinst/domcapabilities.py
This makes the experience of running emulated guests (e.g. riscv64 on x86_64) a lot nicer.
> Add support for maximum CPU mode (cli, gui) and prefer it

- man/virt-install.rst
- man/virt-xml.rst
- tests/test_cli.py
- virtManager/createvm.py
- virtinst/cli.py
- virtinst/install/installertreemedia.py
- virtinst/virtinstall.py
- virtinst/virtxml.py
The former is the preferred spelling and it should always be presented first to the user.
> cli, man: Always list --osinfo before --os-variant

- virtManager/createvm.py
As all major distros support the riscv64 architecture, add it to the list of prioritized architectures. This will move it up in the architecture drop-down menu and thereby easier to find when creating a new VM.
> createvm: prioritize riscv64

- .github/workflows/black.yml
- .pre-commit-config.yaml
- setup.cfg
- tests/meson.build
This adds a basic `pre-commit` config to run `black`, and uses it for code validation in CI
`pre-commit` isn't a requirement here, but it's a simple platform that we can plug in additional code tools and the dev workflow remains the same: like `codespell` in current git, or future things like `flake8` or `ruff`. As a dev, it helps me ensure I don't forget to run tools like `black` before submitting code.
This PR is very bare, just the minimum to get CI to prevent virt-manager.git formatting
from regressing. Things I will do in a follow up PR:
* update HACKING.md etc
* use .git-blame-ignore-revs
* move codespell to pre-commit
* combine codespell and black github actions into one
@pinotree @phrdina any objections?
> Add `pre-commit`, use it to run `black` in CI

- virtinst/install/urldetect.py
Add riscv64 to the list of Debian architectures.
> urlfetcher: add riscv64 architecture for Debian

- virtManager/device/netlist.py
Using qemu-bridge-helper QEMU Session VMs are now able to use host bridge interfaces. Currently only interface named virbr0 is allowed by default but it is possible to change it in `/etc/qemu/bridge.conf`.
We will still keep the usermode network as default.
Resolves: https://github.com/virt-manager/virt-manager/issues/863
> virt-manager: list virtual networks when creating new QEMU Session VM

- tests/data/cli/compare/virt-install-many-devices.xml
- tests/data/cli/compare/virt-install-virtio-sound-device.xml
- tests/test_cli.py
The line:
```bash
--sound model=virtio,streams=4
```
requires libvirt version 10.4.0 (this is when the virtio sound device was added).
This was in the large multi-device test, but I have separated it into an individual test for now.
> Separate model=virtio sound device into an individual test

- virtinst/cli.py
When running virt-install using waypipe the DISPLAY variable is not defined and virt-install will complain that it cannot start virt-viewer.
Check for WAYLAND_DISPLAY as well, DISPLAY is defined only when xwayland is used. In case of waypipe it configures only WAYLAND_DISPLAY.
Move the check before we check for virt-viewer as without display there is no point to check if virt-viewer is installed or not.
Fixes: https://github.com/virt-manager/virt-manager/issues/884
> virt-install: detect wayland in order to start virt-viewer

- tests/test_xmlparse.py
- virtinst/xmlbuilder.py
This PR updates the name validation to allow spaces and disallow `/`, matching QEMU validation.
It also adds test coverage to ensure:
- Names with spaces pass validation
- Names with `/` raise `ValueError`
In response to #740
> Allow space and disallow slash in validation

- man/virt-install.rst
- tests/data/cli/compare/virt-install-cloud-init-options6.xml
- tests/test_cli.py
- virtinst/install/cloudinit.py
- virtinst/install/installer.py
This allows users to specify `meta-data`, `user-data` and `network-config` using URL in addition to local file.
> Add support to get cloud-init config file from URL

- virtManager/storagebrowse.py
#901
Error:
```
DEBUG (cli:195) Uncaught exception:
Traceback (most recent call last):
File "/nix/store/f4iw4ran3xbfxqfcqmc0l69gj33pq3lq-virt-manager-5.0.0/share/virt-manager/virtManager/storagebrowse.py", line 162, in _browse_clicked
return self._browse_local()
^^^^^^^^^^^^^^^^^^^^
File "/nix/store/f4iw4ran3xbfxqfcqmc0l69gj33pq3lq-virt-manager-5.0.0/share/virt-manager/virtManager/storagebrowse.py", line 190, in _browse_local
start_folder=start_folder,
^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'start_folder' where it is not associated with a value
```
> fix: set default start_folder value to None

- virtManager/details/console.py
logind now supports a new key binding https://github.com/systemd/systemd/pull/29542 Ctrl+Alt+Shift+Esc that emits SecureAttentionKey to allow login managers to start or switch back to the greeter
> Add Ctrl+Alt+Shift+Esc key command for logind's SecureAttentionKey

- tests/test_dist.py
- tests/uitests/test_about.py
- virtManager/details/sshtunnels.py
- virtinst/devices/__init__.py
- virtinst/diskbackend.py
- virtinst/domain/__init__.py
- virtinst/virtinstall.py
- virtinst/xmlutil.py
According to PEP8 [1], 'l' (lowercase 'L') is name to avoid, as potentially hard to read.
Switch the occurrences to more clear names representing better what the variables/parameters represent (e.g. "tunnel", "data", etc). In case the variable/parameter is really a list, use "lst" to not use "list" and override the builtin.
Additionally, a 'w' variable was changed for consistency with the 'l' changed in the line above it.
There should be no behaviour changes.
[1] https://peps.python.org/pep-0008/#names-to-avoid
> chore: avoid using 'l' as variable/parameter name

- pyproject.toml
- tests/test_xmlparse.py
- tests/utils.py
Enable the flake8-pytest-style rules for ruff, checking for commit style issues and inconsistencies in pytest-based tests.
PT011 & PT012 errors are already ignored in tests (there are only few), and PT028 was fixed by renaming an helper function so it is not mistaken as test. There are no errors beside those.
> chore: enable flake8-pytest-style for ruff

- tests/data/cli/compare/virt-install-x86_64-launch-security-tdx-full.xml
- tests/data/cli/compare/virt-install-x86_64-launch-security-tdx-qgs.xml
- tests/data/cli/compare/virt-install-x86_64-launch-security-tdx.xml
- tests/test_cli.py
- virtinst/cli.py
- virtinst/domain/launch_security.py
A minimal config to enable TDX, with support for attestation would be
$ virt-install
...args...
--boot uefi \
--machine q35 \
--launchSecurity type=tdx,quoteGenerationService=on
NB, libvirt support for TDX is NOT yet merged, and this PR XML does NOT patch the XML of the latest patches - it is written based on my suggested XML rename of one of the elements. 
IOW this PR must wait until the final libvirt merge.
> virtinst: add support for creating TDX guests

- tests/data/cli/compare/virt-install-aarch64-kvm-gic.xml
- tests/data/cli/compare/virt-install-aarch64-kvm-import.xml
- tests/data/cli/compare/virt-install-aarch64-machdefault.xml
- tests/data/cli/compare/virt-install-aarch64-machvirt.xml
- tests/data/cli/compare/virt-install-aarch64-win11.xml
- tests/data/cli/compare/virt-install-arm-defaultmach-f20.xml
- tests/data/cli/compare/virt-install-arm-kvm-import.xml
- tests/data/cli/compare/virt-install-arm-virt-f20.xml
- tests/test_cli.py
- virtinst/devices/disk.py
- virtinst/devices/video.py
- virtinst/guest.py
Broadly speaking, this pull request addresses the following two problems:
1. It was assumed virtio is supported on the Arm virt machine, but Windows does not.
2. Hyper-V features are assumed to be available on every architecture, but they are specific to x86.
Note that there are remaining problems that need to be addressed in libvirt or libosinfo. Please see commit 6621e736d64e0e9838a6d906d7841e627f4838e6 for details.
Linaro provides concrete instructions to test Windows on Arm64: https://linaro.atlassian.net/wiki/spaces/WOAR/pages/28914909194/windows-arm64+VM+using+qemu-system
> Fix for Windows on Arm64

- virtManager/addhardware.py
- Add bhyve to a list of guest types that support virtio device type
- Do not include rtl8139 for bhyve
> addhardware: network: adjust supported network devices for bhyve

- virtinst/install/cloudinit.py
Refactor creation of cloud-init config files introduced a bug where we stopped including empty meta-data file.
Introduced-by: 5b2d0997a1d2d213b17c227169da64e2fa7d09a6
Fixes: https://github.com/virt-manager/virt-manager/issues/975
> virtinst: cloudinit: include empty meta-data file
