virt-manager/virt-manager

man/virt-install.pod
Fedora 20 and 25 are end-of-life. Update to a modern Fedora version.
=> doc: update Fedora versions

virtinst/connection.py
_fetch_all_pools_raw() and _fetch_vols_raw() have a race condition where
a pool/volume may disappear (from parallel libvirt operations) in
between enumerating and inspecting the objects.
_fetch_vols_raw() already expected that failure in the loop, but not for
the initial storagePoolLookupByName() call.
Also tighten the expected exception: This *should* crash on errors like
AttributeError or SystemExit, just not on dynamic libvirt errors. (Bare
exceptions are highly frowned upon in Python)
https://bugzilla.redhat.com/show_bug.cgi?id=1894359
=> virtinst: Fix TOCTOU in pool and volume enumeration

tests/data/cli/compare/virt-install-many-devices.xml, tests/test_cli.py, virtinst/cli.py, virtinst/devices/controller.py
Signed-off-by: Igor Ryzhov <iryzhov@nfware.com>
=> virtinst: add support for controller target subelement

virtinst/connection.py
Similar to commit 49a01b5482, _fetch_all_domains_raw() has a race
condition where a domain may disappear (from parallel libvirt
operations) in between enumerating and inspecting the objects.
Ignore these missing domains instead of crashing.
https://bugzilla.redhat.com/show_bug.cgi?id=1901081
-----
I tortured this with the reproducer attached to bugzilla, and I can't get it to crash any more.
=> virtinst: Fix TOCTOU in domain enumeration

.pylintrc, COPYING, NEWS.md, man/virt-install.rst, man/virt-manager.rst, man/virt-xml.rst, virt-clone, virt-install, virt-manager, virt-xml
Review comments are very welcome.
=> Simple maintenance improvements

man/virt-install.rst, tests/data/cli/cloudinit/network-config.txt, tests/test_cli.py, virtinst/cli.py, virtinst/install/cloudinit.py
This MR add network-config option to the `virt-install --cloud-init` which implement the #294
=> cli: --cloud-init add network-config option

setup.py
=> Install before updating cache & compiling schemas

virtManager/createvol.py
As per @crobinso's request, all details of what the change does is in the related issue.
Closes #487
=> Support creating sparse volumes on ZFS pools

man/virt-manager.rst, virtManager/engine.py, virtManager/virtmanager.py
I created this PR on behalf of @xfgusta. See #149 for discussion. I also tested the code and it seems to work.
=> Show systray option

tests/test_cli.py, virtinst/devices/disk.py
=> fix: strip away `file://` protocol

tests/data/capabilities/kvm-aarch64-domcaps.xml, tests/data/capabilities/kvm-aarch64.xml, tests/data/cli/compare/virt-install-aarch64-cloud-init.xml, tests/data/cli/compare/virt-install-aarch64-firmware-no-override.xml, tests/data/cli/compare/virt-install-aarch64-kvm-gic.xml, tests/data/cli/compare/virt-install-aarch64-kvm-import.xml, tests/test_capabilities.py, virtinst/domcapabilities.py
=> tests: Update aarch64 capabilities

tests/data/capabilities/kvm-ppc64le-domcaps.xml, tests/data/capabilities/kvm-ppc64le.xml, tests/data/cli/compare/virt-install-ppc64le-kvm-import.xml, tests/test_capabilities.py
Plus additional test coverage.
=> tests: Update ppc64le capabilities

INSTALL.md
Commit 1f80a62239e443a6fb120d341359682ed6e44c83 renamed `virt-manager.spec` to be `virt-manager.spec.in`. This PR adjusts the `INSTALL.md` source to changes.
=> update `virt-manager.spec.in` reference

tests/data/cli/compare/virt-install-many-devices.xml, tests/data/cli/compare/virt-install-qemu-plain.xml, tests/data/cli/compare/virt-install-singleton-config-1.xml, tests/data/cli/compare/virt-install-xen-pv.xml, tests/test_cli.py, virtinst/cli.py, virtinst/devices/input.py, virtinst/guest.py
=> virt-install: some fixes around `--input` handling

man/virt-clone.rst, tests/data/cli/compare/virt-clone-clone-nvram.xml, tests/data/cli/virtclone/clone-disk-noexist.xml, tests/data/cli/virtclone/clone-nvram-auto.xml, tests/test_cli.py, tests/test_disk.py, virtinst/cloner.py, virtinst/storage.py
See individual patches for details
=> virt-clone: misc fixes

virt-manager.spec.in
=> rpm spec: fixes from fedora+centos

.codespellrc, .github/workflows/codespell.yml, tests/data/codespell_dict.txt, tests/meson.build
- move the codespell configuration to a config file
- tweak the codespell configuration to match the sources
- add a github workflow to run codespell in PRs
=> Codespell improvements

.codespellrc, NEWS.md
Fix few typos in it, and let it be analysed by `codespell`.
=> NEWS.md: typo fixes

tests/data/cli/compare/virt-install-many-devices.xml, tests/test_cli.py, virtManager/device/netlist.py, virtinst/devices/interface.py
To fix issue #870 
This maps --network source.dev= to the XML:
```xml
<interface type="vdpa">
<source dev="/dev/vhost-vdpa-0"/>
</interface>
```
=> Add support for vDPA network device

tests/uitests/lib/_node.py, tests/uitests/test_createvm.py, tests/uitests/test_livetests.py, tests/uitests/test_manager.py
Some uitests fixes when running on f41, and code coverage for newish commits
=> uitests fixes and coverage

tests/data/urldetect/debian/debian-8.10.0-badarch-netinst.iso/.disk/info, tests/test_urldetect.py, virtinst/install/urldetect.py
Resolves https://github.com/virt-manager/virt-manager/issues/871
=> Improve Debian ISO detection

data/virt-manager.desktop.in
=> Add keywords to virt-manager.desktop.in
